# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mycroft92's Blog
email: madhukaryerraguntla@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Random ramblings of a jack of all trades.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mycroft92.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lean_panda
facebook_username: madhukar9x
github_username:  mycroft92
reddit_username: mycroft92
disqus.shortname: "mycroft92-github-io"




# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-octicons

#mydefines
mytags:
  - Duelyst
  - Decks
  - Programming
  - Music

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - .gitignore
#   - .git/
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
